[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.testnet]
otc_market = "GUoV8eVV4udV5bngnkdvmUjhTRSmsMV4GZyC8dq6kTh1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "/home/sasha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/omnichain/*.ts"
