[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.testnet]
otc_market = "2fDGk1xhuKokYxG8xdoP8JuFcsP86rp2JZ52oChRuf8j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/omnichain/*.ts"
